import { useRouter } from "next/router";
import { AnimatePresence, motion } from "framer-motion";

import Head from "next/head";
import styles from "../styles/Home.module.css";

import Layout from "../components/Layout";
import Landing from "../components/Landing";
import Projects from "../components/Projects";

import client from "../client";

export default function Home({ projects }) {
  const location = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <AnimatePresence exitBeforeEnter>
        <motion.div
          location={location}
          key={location.pathname}
          initial={{ y: 0, opacity: 1 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: -500, opacity: 1 }}
          transition={{ duration: 1, ease: "easeIn" }}
        > */}
          <Layout>
            <div>
              <Landing />
            </div>
            <div>
              <Projects projects={projects} />
            </div>
          </Layout>
        {/* </motion.div>
      </AnimatePresence> */}
    </div>
  );
}

export async function getStaticProps() {
  const projects = await client.fetch(`
  *   [_type == "projects"]|order(orderRank){"image": image.asset->{url, "dimensions": metadata.dimensions}, alt}`);

  return {
    props: {
      projects,
    },
    revalidate: 10,
  };
}
